version: 1.0.{build}

cache:
  - packages
  
install:
  - nuget restore src\BeYourMarket.sln

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration
configuration: Release

build:
  project: src/BeYourMarket.sln
  publish_wap: true
  publish_wap_xcopy: true
  publish_nuget: true
  verbosity: minimal
  include_nuget_references: true

artifacts:
  # pushing a single file
  - path: .\src\BeYourMarket.Web
    name: beyourmarket
  
environment:
    COVERALLS_REPO_TOKEN:  
       secure: NdkuJqVjkZpPgi36NtKtRYyvP3ey+jpOe9ABsf99Sqk1/93T7RgobgZln/K66T2G
    CODECOV_TOKEN:  
       secure: 57QwSC01T1avA49saB0GxunhOv5fzy5CtO7lqTD4bycPjft+IS9R5a+nL1wFQzZ2
       
after_test: 
  - .\src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\src\Tests\BeYourMarket.Test\bin\Debug\BeYourMarket.Test.dll" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml
  - .\src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover .\coverage.xml

